# Generated by Django 5.1.1 on 2024-10-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_genders_roles_remove_user_role_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Male"), (2, "FEMALE"), (3, "Other")],
                null=True,
            ),
        ),
    ]
