# Generated by Django 5.1.4 on 2025-01-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_genders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genders',
        ),
    ]
