# Generated by Django 5.1.4 on 2025-02-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_genders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
