# Generated by Django 5.1.4 on 2025-10-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_service_ticketpriority_type_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlCommand',
            fields=[
                ('command_id', models.AutoField(primary_key=True, serialize=False)),
                ('command_text', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
