# Generated by Django 5.1.4 on 2025-10-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_sqlcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
