# Generated by Django 5.1.4 on 2025-10-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_ticketlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketState',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='field_changed',
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='old_value',
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='ticket_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.ticketstate'),
        ),
    ]
