# Generated by Django 5.1.4 on 2025-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_ticketstate_remove_ticketlog_field_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='entry_type',
            field=models.CharField(choices=[('fetched', 'Fetched'), ('auto-assign', 'Auto Assign'), ('manual-update', 'Manual Update'), ('override', 'Override'), ('sla-update', 'SLA Update'), ('closed', 'Ticket Closed')], default='auto-assign', max_length=50),
        ),
    ]
