# Generated by Django 5.1.4 on 2025-10-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_ticketlog_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='entry_type',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('auto-assign', 'Auto Assign'), ('manual-update', 'Manual Update'), ('override', 'Override'), ('sla-update', 'SLA Update'), ('closed', 'Ticket Closed')], default='auto-assign', max_length=50),
        ),
    ]
