# Generated by Django 5.1.4 on 2025-10-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_alter_ticketlog_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='entry_type',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('auto-assign', 'Auto Assign'), ('manual-update', 'Manual Update'), ('type-update', 'Type Update'), ('service-update', 'Service Update'), ('priority-update', 'Priority Update'), ('owner-update', 'Owner Update'), ('state-update', 'State Update'), ('closed', 'Ticket Closed')], default='auto-assign', max_length=50),
        ),
    ]
