# Generated by Django 5.1.4 on 2025-10-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_ticketlog_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='ticket_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
