# Generated by Django 5.1.4 on 2025-10-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_ticketlog_ticket_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='ticket_owner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
