# Generated by Django 5.1.4 on 2025-11-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_location_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
