# Generated by Django 5.1.4 on 2025-11-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='status',
        ),
        migrations.AddField(
            model_name='roster',
            name='fri_status',
            field=models.CharField(choices=[('ON', 'On Duty'), ('OFF', 'Off'), ('LEAVE', 'Leave')], default='ON', max_length=5),
        ),
        migrations.AddField(
            model_name='roster',
            name='mon_status',
            field=models.CharField(choices=[('ON', 'On Duty'), ('OFF', 'Off'), ('LEAVE', 'Leave')], default='ON', max_length=5),
        ),
        migrations.AddField(
            model_name='roster',
            name='sat_status',
            field=models.CharField(choices=[('ON', 'On Duty'), ('OFF', 'Off'), ('LEAVE', 'Leave')], default='ON', max_length=5),
        ),
        migrations.AddField(
            model_name='roster',
            name='sun_status',
            field=models.CharField(choices=[('ON', 'On Duty'), ('OFF', 'Off'), ('LEAVE', 'Leave')], default='ON', max_length=5),
        ),
        migrations.AddField(
            model_name='roster',
            name='thu_status',
            field=models.CharField(choices=[('ON', 'On Duty'), ('OFF', 'Off'), ('LEAVE', 'Leave')], default='ON', max_length=5),
        ),
        migrations.AddField(
            model_name='roster',
            name='tue_status',
            field=models.CharField(choices=[('ON', 'On Duty'), ('OFF', 'Off'), ('LEAVE', 'Leave')], default='ON', max_length=5),
        ),
        migrations.AddField(
            model_name='roster',
            name='wed_status',
            field=models.CharField(choices=[('ON', 'On Duty'), ('OFF', 'Off'), ('LEAVE', 'Leave')], default='ON', max_length=5),
        ),
    ]
