# Generated by Django 5.1.4 on 2025-11-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_remove_roster_status_roster_fri_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='queue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
