# Generated by Django 5.1.4 on 2025-11-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_location_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='ticket_queue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
